#include <jni.h>
#include "ReactNativeListOnLoad.hpp"
#include "JHybridUiListModule.h"

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *)
{
  return facebook::jni::initialize(vm, []() {
      margelo::nitro::reactnativelist::registerAllNatives();
      // Register additional native methods (not generated by Nitrogen)
      margelo::nitro::reactnativelist::JHybridUiListModule::registerNatives();
  });
}
