#include <jni.h>
#include "ReactNativeListOnLoad.hpp"
#include "JHybridUiListModule.h"

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *)
{
  auto result = margelo::nitro::reactnativelist::initialize(vm);
  // Register additional native methods (not generated by Nitrogen)
  margelo::nitro::reactnativelist::JHybridUiListModule::registerNatives();
  return result;
}
