type ReactFabricMirrorModule = typeof import('./ReactFabricMirror')

// This has to be a function so that its a worklet which can be called on the UI runtime.
// Never import the ReactFabricMirrorModule directly from non-worklet code!
export function getReactFabricRenderer(): ReactFabricMirrorModule {
  'worklet'
  // This file is generated by `bun bundle:js`. It contains setting up the React instance on the UI runtime.
  // This is what will do the "react render phase" of our react tree. Note that this is seperate from the
  // fabric tree rendering + mounting. This is just react stuff.
  return require('@leonsilicon/react-native-list/src/renderer/react/ReactFabricMirror.bundle')
}
